[env:esp32-s3-super-mini]
platform  = espressif32
board     = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200

; BLE/Bluetooth library
lib_deps = 
	h2zero/NimBLE-Arduino @ ^1.4
	adafruit/Adafruit NeoPixel @ ^1.12.0

; Exact hardware config for ESP32-S3 Super Mini
board_build.mcu        = esp32s3
board_build.f_cpu      = 240000000L
board_build.flash_size = 4MB
board_build.flash_mode = qio
board_upload.flash_size = 4MB

build_flags = 
	-DCORE_DEBUG_LEVEL=0
	-D ARDUINO_USB_CDC_ON_BOOT=1